
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrxwmpmsziwtslxxjrsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyeHdtcG1zeml3dHNseHhqcnNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTI3NDIsImV4cCI6MjA2MTI4ODc0Mn0.5CLPvarS-Ps5i14V5BtkcFY_iOIMHmCOg5AHak_1v7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Log configuration for debugging
console.log("Supabase client initialized with URL:", SUPABASE_URL);
